name: Verify API Key

on:
  push:
    branches:
      - main

jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Print API Key
        run: echo "API Key: ${{ secrets.API_KEY}}"

      - name: Test API Key
        run: |
          curl -H "Authorization: Bearer ${{ secrets.API_KEY }}" https://api.yourservice.com/test-endpoint
