jobs:
  example-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        
      - name: Use API Key
        run: echo "API_KEY=${{ secrets.API_KEY }}" >> $GITHUB_ENV

      - name: Print API Key (For Debugging - Will Be Masked)
        run: echo "The API Key is: $API_KEY"
        env:
          API_KEY: ${{ secrets.API_KEY }}
