name: API_KEY Workflow

on: [push]  # This triggers the workflow on push events

jobs:
  example-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set API Key as an environment variable
        run: echo "API_KEY=${{ secrets.API_KEY }}" >> $GITHUB_ENV
