name: Example Workflow

on: [push]  # Triggers the workflow on push

jobs:
  example-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set API Key as an environment variable
        run: echo 'API_KEY=${{ secrets.API_KEY }}' >> $GITHUB_ENV

      - name: Print API Key (For Debugging - Will Be Masked)
       
        env:
          API_KEY: ${{ secrets.API_KEY }}
